# Generated by Django 6.0 on 2025-12-05 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("isp", models.CharField(blank=True, max_length=255, null=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("visit_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="iplogger_vi_ip_addr_b96efa_idx"
                    ),
                    models.Index(
                        fields=["last_seen"], name="iplogger_vi_last_se_c2d327_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(blank=True, max_length=10)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="iplogger.visitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="iplogger_vi_timesta_3aadf9_idx"
                    ),
                    models.Index(fields=["path"], name="iplogger_vi_path_cf9e65_idx"),
                ],
            },
        ),
    ]
